name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
          
      - name: Run tests
        run: go test -v ./...
        
      - name: Build all platforms
        run: |
          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -o adrgen-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o adrgen-windows-arm64.exe
          
          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -o adrgen-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o adrgen-linux-arm64
          
          # Build for macOS
          GOOS=darwin GOARCH=amd64 go build -o adrgen-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o adrgen-darwin-arm64
          
          # Create SHA256 checksums
          sha256sum adrgen-* > SHA256SUMS.txt
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            adrgen-windows-amd64.exe
            adrgen-windows-arm64.exe
            adrgen-linux-amd64
            adrgen-linux-arm64
            adrgen-darwin-amd64
            adrgen-darwin-arm64
            SHA256SUMS.txt
          generate_release_notes: true 